[workspace]
members = [
  "crates/ecashmesh-api",
  "crates/ecashmesh-cashu",
  "crates/ecashmesh-core",
  "crates/ecashmesh-fedimint",
  "crates/ecashmesh-lab-runner",
]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bansalayush247/ecashmesh"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
